apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-storage
spec:
  storageClassName: default-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
