apiVersion: apps/v1
kind: Deployment
metadata:
  name: crs-zookeeper-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-cluster
  template:
    metadata:
      labels:
        component: zookeeper-cluster
        app: zookeeper-cluster
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        securityContext:
          runAsUser: 0 
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        readinessProbe:
          exec:
            command:
            - /opt/bitnami/zookeeper/bin/zkCli.sh
          initialDelaySeconds: 10
          timeoutSeconds: 20
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /opt/bitnami/zookeeper/bin/zkCli.sh
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 5
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes" 
        - name: ZOO_INIT_LIMIT
          value: "5"
        - name: ZOO_SYNC_LIMIT
          value: "2"
        - name: ZOO_SERVERS
          value: 10.158.0.7:2888:3888
        volumeMounts:
            - name: kafka-storage
              mountPath: /bitnami/zookeeper
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
              claimName: kafka-storage
